
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.4'
version_full = 'e6c71bdb57bdbe82cd8ea9d25ca574cb0ae99279'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

