
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.4'
version_full = '917abacee145bef7506478e005827ef1bb2a9e27'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

